#! /bin/bash

# arguments
FILE_PATH=""
MAKE_TRACKLET=0
TRACKLET_DIR=""

#SCRIPT_PATH=$(readlink -f "$0")
#SCRIPT_DIR=$(dirname "$SCRIPT")
#sudo chmod 755 $scriptdir/../object_tracker/src/detector.py $scriptdir/../object_tracker/src/detector.py

# help function
function usage()
{
    echo "  -----------"
    echo "  |Arguments|"
    echo "  -----------"
    echo "  Help: -h --help"
    echo "  Bag file path: --file_path"
    echo "  Make tracklet: --tracklet"
    echo ""
}

# parse argument
while [ "$1" != "" ]; do
    PARAM="$1"
    VALUE="$2"
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        --file_path)
            FILE_PATH=$VALUE
            shift
            ;;
        --tracklet)
            MAKE_TRACKLET=1
            TRACKLET_DIR=$VALUE
            shift
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo -e "\e[92mPublish image and lidar points in $FILE_PATH\e[0m"
roslaunch bag_player.launch bag_file_path:=$FILE_PATH make_tracklet:=$MAKE_TRACKLET tracklet_dir:=$TRACKLET_DIR
