#! /bin/bash

#SCRIPT_PATH=$(readlink -f "$0")
#SCRIPT_DIR=$(dirname "$SCRIPT")
#sudo chmod 755 $scriptdir/../object_tracker/src/detector.py $scriptdir/../object_tracker/src/detector.py

echo -e "\e[92mStart object_tracker\e[0m"
roslaunch object_tracker.launch
