#! /bin/bash

# arguments
USE_CPP_NODE=0

#SCRIPT_PATH=$(readlink -f "$0")
#SCRIPT_DIR=$(dirname "$SCRIPT")
#sudo chmod 755 $scriptdir/../object_tracker/src/detector.py $scriptdir/../object_tracker/src/detector.py

# help function
function usage()
{
    echo "  -----------"
    echo "  |Arguments|"
    echo "  -----------"
    echo "  Help: -h --help"
    echo "  Use cpp node: --use_cpp_node"
    echo ""
}

# parse argument
while [ "$1" != "" ]; do
    PARAM="$1"
    VALUE="$2"
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        --use_cpp_node)
            USE_CPP_NODE=1
            echo "use cpp node"
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo -e "\e[92mStart object_tracker\e[0m"
roslaunch object_tracker.launch use_cpp_node:=$USE_CPP_NODE
